<a href="https://colab.research.google.com/github/19PA1A04B1/10-03-2020/blob/master/NUMPY_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
a = np.arange(20).reshape(4, 5) 
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [4]:
a[a<4]=-1
a

array([[-1, -1, -1, -1,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [5]:
a=np.sin(a)*10
a

array([[-8.41470985, -8.41470985, -8.41470985, -8.41470985, -7.56802495],
       [-9.58924275, -2.79415498,  6.56986599,  9.89358247,  4.12118485],
       [-5.44021111, -9.99990207, -5.36572918,  4.20167037,  9.90607356],
       [ 6.5028784 , -2.87903317, -9.61397492, -7.50987247,  1.4987721 ]])

In [6]:
a[1:3,1:2]


array([[-2.79415498],
       [-9.99990207]])

In [8]:
a[-1,-1]

1.4987720966295235

In [9]:
a.T

array([[-8.41470985, -9.58924275, -5.44021111,  6.5028784 ],
       [-8.41470985, -2.79415498, -9.99990207, -2.87903317],
       [-8.41470985,  6.56986599, -5.36572918, -9.61397492],
       [-8.41470985,  9.89358247,  4.20167037, -7.50987247],
       [-7.56802495,  4.12118485,  9.90607356,  1.4987721 ]])

In [10]:
a.reshape(2,10)

array([[-8.41470985, -8.41470985, -8.41470985, -8.41470985, -7.56802495,
        -9.58924275, -2.79415498,  6.56986599,  9.89358247,  4.12118485],
       [-5.44021111, -9.99990207, -5.36572918,  4.20167037,  9.90607356,
         6.5028784 , -2.87903317, -9.61397492, -7.50987247,  1.4987721 ]])

In [11]:
a[-1,]

array([ 6.5028784 , -2.87903317, -9.61397492, -7.50987247,  1.4987721 ])

In [13]:
a.ravel()

array([-8.41470985, -8.41470985, -8.41470985, -8.41470985, -7.56802495,
       -9.58924275, -2.79415498,  6.56986599,  9.89358247,  4.12118485,
       -5.44021111, -9.99990207, -5.36572918,  4.20167037,  9.90607356,
        6.5028784 , -2.87903317, -9.61397492, -7.50987247,  1.4987721 ])